# Generated by Django 2.0 on 2021-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(default='Password', max_length=100)),
                ('Role', models.CharField(default='Role', max_length=50)),
                ('Is_Verified', models.BooleanField(default=False)),
                ('Account_Status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive')], default='ACTIVE', max_length=10)),
                ('Account_Created_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
