# Generated by Django 2.0 on 2021-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadmin',
            name='OTP',
            field=models.BigIntegerField(default=123456),
        ),
    ]
