# Generated by Django 2.0 on 2021-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_aadmin_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAndComplaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(default='Name', max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('Subject', models.CharField(default='Feedback', max_length=100)),
                ('Message', models.TextField(max_length=5000)),
            ],
        ),
    ]
