# Generated by Django 2.0 on 2021-11-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_feedbackandcomplaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackandcomplaints',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.AAdmin'),
        ),
    ]
