# Generated by Django 2.0 on 2021-11-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_feedbackandcomplaints_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackandcomplaints',
            name='admin',
        ),
    ]
