# Generated by Django 2.0 on 2021-11-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_feedbackandcomplaints_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackAndComplaints',
            new_name='FeedbackOrComplaints',
        ),
    ]
