from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.IndexPage, name="indexPage"),
    path('register-page', views.RegisterPage, name="registerPage"),
    path('register-user-page', views.RegisterUserPage, name="registerUserPage"),
    path('login-page', views.LoginPage, name="loginPage"),
    path('login-user-page', views.LoginUserPage, name="loginUserPage"),
    path('log-out-page', views.LogOutPage, name="logOutPage"),
    path('delete-account-page', views.DeleteAccountPage, name="deleteAccountPage"),
    path('forgot-password-page', views.ForgotPasswordPage, name="forgotPasswordPage"),
    path('email-verification-page', views.EmailVerificationPage, name="emailVerificationPage"),
    path('otp-verification-page', views.OTPVerificationPage, name="otpVerificationPage"),
    path('password-changing-page', views.PasswordChangingPage, name="passwordChangingPage"),
    path('user-profile-page', views.UserProfilePage, name="userProfilePage"),
    path('update-profile-page/<int:pk>', views.UpdateProfilePage, name="updateProfilePage"),
    path('find-artist',views.FindArtist,name="findartist"),
    path('find-artist-page', views.FindArtistsPage, name="findArtistsPage"),
    path('book-artist-page/<int:pk>', views.BookArtistPage, name="bookArtistPage"),
    path('book-artist-requests-page/<int:pk>', views.BookArtistRequestsPage, name="bookArtistRequestsPage"),
    path('requests-page', views.RequestsPage, name="requestsPage"),
    path('show-requests-page/<int:pk>', views.ShowRequestsPage, name="showRequestsPage"),
    path('upate-requests-page/<int:pk>', views.UpdateRequestsPage, name="updateRequestsPage"),
    path('payment-process-page/<int:pk>', views.PaymentProcessPage, name="paymentProcessPage"),
    path('payment-success-page/<int:pk>', views.PaymentSuccessPage, name="paymentSuccessPage"),
    path('dashboard-page', views.DashboardPage, name="dashboardPage"),
    path('delete-account-page/<int:pk>', views.DeleteAccountPage, name="deleteAccountPage"),
    path('give-reviews-Page/<int:pk>', views.GiveReviewsPage, name="reviewsPage"),
    path('enter-reviews/<int:pk>', views.EnterReviews, name="enterReviews"),
    path('submit-reviews/<int:pk>', views.SubmitReviews, name="submitReviews"),
    path('show-submitted-review/<int:pk>', views.ShowSubmittedReview, name="showSubmittedReview"),
    path('edit-reviews/<int:pk>', views.EditReviews, name="editReviews"),
    path('all-reviews/<int:pk>', views.AllReviews, name="allReviews"),
    path('submit-feedback-and-complaints', views.SubmitFeedbackAndComplaints, name="submitFeedbackAndComplaints"),
    path('feedback-and-complaints', views.FeedbackAndComplaints, name="feedbackAndComplaints"),
    path('all-artist-page', views.AllArtistPage, name="allArtistPage"),
    path('all-visitor-page', views.AllVisitorPage, name="allVisitorPage"),
    path('all-feedback-and-complaints', views.AllFeedbackAndComplaints, name="allFeedbackAndComplaints"),
]