# Generated by Django 2.0 on 2021-09-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0004_remove_aartist_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aartist',
            name='Profession',
            field=models.CharField(default='Profession', max_length=100),
        ),
    ]
