# Generated by Django 2.0 on 2021-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0006_remove_aartist_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aartist',
            name='Myself',
            field=models.CharField(default='I am....', max_length=255),
        ),
    ]
