# Generated by Django 2.0 on 2021-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0007_aartist_myself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aartist',
            name='Birthdate',
            field=models.DateField(),
        ),
    ]
