# Generated by Django 2.0 on 2021-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0008_auto_20210928_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='aartist',
            name='Profession',
            field=models.CharField(default='Profession', max_length=100),
        ),
    ]
