# Generated by Django 2.0 on 2021-10-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0008_auto_20210928_1107'),
        ('Artist', '0010_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(default='Event name', max_length=100)),
                ('Place', models.CharField(default='Event place', max_length=200)),
                ('Date', models.DateField()),
                ('Description', models.TextField(max_length=5000)),
                ('Files', models.ImageField(upload_to='media/event/')),
                ('artistkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artist.AArtist')),
                ('visitorkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Visitor.VVisitor')),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='visitorkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Visitor.VVisitor'),
        ),
    ]
