# Generated by Django 2.0 on 2021-10-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0012_auto_20211014_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequests',
            name='Files',
        ),
        migrations.AddField(
            model_name='bookingrequests',
            name='Maximum_Budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingrequests',
            name='Minimum_Budget',
            field=models.IntegerField(default=0),
        ),
    ]
