# Generated by Django 2.0 on 2021-10-21 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0013_auto_20211021_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequests',
            old_name='Date',
            new_name='Event_Date',
        ),
        migrations.AddField(
            model_name='bookingrequests',
            name='Request_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingrequests',
            name='Description',
            field=models.TextField(default='About Event...', max_length=5000),
        ),
    ]
