# Generated by Django 2.0 on 2021-10-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0014_auto_20211021_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequests',
            name='Status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
