# Generated by Django 2.0 on 2021-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0016_bookingrequests_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Visitor_name',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Review',
            field=models.TextField(default='Your Comments....', max_length=5000),
        ),
    ]
