# Generated by Django 2.0 on 2021-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0017_auto_20211111_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='On_Budget',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='On_Time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='Rate',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1),
        ),
    ]
