# Generated by Django 2.0 on 2021-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0018_auto_20211111_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Rate',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=10),
        ),
    ]
