# Generated by Django 2.0 on 2021-11-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0020_auto_20211111_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artist.BookingRequests'),
        ),
    ]
