# Generated by Django 2.0 on 2021-11-13 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0021_reviews_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='visitor',
        ),
    ]
