# Generated by Django 2.0 on 2021-11-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0008_auto_20210928_1107'),
        ('Artist', '0022_auto_20211113_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Artist.AArtist'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Visitor.VVisitor'),
        ),
    ]
