# Generated by Django 2.0 on 2021-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0023_auto_20211113_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='Rate',
            field=models.IntegerField(),
        ),
    ]
