# Generated by Django 2.0 on 2021-09-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='First name', max_length=100)),
                ('Lastname', models.CharField(default='Last name', max_length=100)),
                ('Emailaddr', models.EmailField(default='E-mail Address', max_length=100, unique=True)),
                ('Password', models.CharField(default='Password', max_length=100)),
                ('Repeatpassword', models.CharField(default='Repeat Password', max_length=100)),
                ('Countryflag', models.ImageField(default='abc.png', upload_to='flag')),
                ('Nationality', models.CharField(default='Your Country Name', max_length=50)),
                ('Currentaddr', models.CharField(default='Current Address', max_length=255)),
                ('Permanentaddr', models.CharField(default='Permanent Address', max_length=255)),
                ('Birthdate', models.DateField(auto_now_add=True)),
                ('Mobileno', models.BigIntegerField(default='123')),
                ('Gender', models.CharField(default='Gender', max_length=10)),
                ('ProfilePic', models.ImageField(default='abc.png', upload_to='profile')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.AAdmin')),
            ],
        ),
    ]
