# Generated by Django 2.0 on 2021-09-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_auto_20210918_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vvisitor',
            name='Countryflag',
            field=models.ImageField(default='abc.png', upload_to='media/flag/'),
        ),
        migrations.AlterField(
            model_name='vvisitor',
            name='ProfilePic',
            field=models.ImageField(default='abc.png', upload_to='media/profile/'),
        ),
    ]
