# Generated by Django 2.0 on 2021-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0003_auto_20210918_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vvisitor',
            name='Countryflag',
        ),
        migrations.AlterField(
            model_name='vvisitor',
            name='Nationality',
            field=models.CharField(default='Country Name', max_length=50),
        ),
    ]
