# Generated by Django 2.0 on 2021-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0005_auto_20210920_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vvisitor',
            name='Mobileno',
            field=models.BigIntegerField(default=123),
        ),
    ]
