# Generated by Django 2.0 on 2021-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0006_auto_20210920_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvisitor',
            name='Myself',
            field=models.CharField(default='I am....', max_length=255),
        ),
    ]
